"""
test_inversion.py — Week-3 source inversion (physics/inversion.py).

Closed-loop philosophy, same as the rest of the suite: build readings from the
forward model for a KNOWN source, then check the inverse recovers it. Because the
data is generated by the very model the inverse fits, a good optimiser must land on
the truth to near machine tolerance (noiseless) — so these pin both the math
(linear-in-Q closed form, stability looping) and the optimiser (shrinking grid).

All pure numpy, no network, no scipy.
"""
import numpy as np
import pytest

from physics.plume import CH4_BACKGROUND, predict_ppm
from physics.sensor_sim import SENSOR_NOISE_PPM
from physics.fieldtest import InversionPoint
from physics import inversion


# Geometry shared by the recovery tests: source west of a fan of downwind sensors
# (wind FROM the west, 270°, so downwind = east). All sensors sit 40–110 m downwind,
# inside the σ table, at varied crosswind offsets so (x, y) is well constrained.
SENSORS = np.array([[40.0, 0.0], [70.0, 12.0], [95.0, -18.0], [110.0, 6.0]])
WIND_U, WIND_DIR, STAB, H, Z = 2.0, 270.0, 4, 1.0, 1.0


def _truth_points(true_src, Q_true, sigma=0.1, stability=STAB,
                  sensors=SENSORS, wind_dir=WIND_DIR):
    """Noiseless InversionPoints for a known source — excess from the forward model.

    ``sensors``/``wind_dir`` default to the shared 270° geometry; the non-cardinal
    round-trip test overrides them (the defaults keep every other caller unchanged).
    """
    total = predict_ppm(true_src, Q_true, WIND_U, wind_dir, H, stability, sensors, z=Z)
    excess = total - CH4_BACKGROUND
    return [
        InversionPoint(
            mean_excess_ppm=float(e), sigma_ppm=sigma, n_window=60, window=(0, 60),
            mean_raw_ppm=float(e) + CH4_BACKGROUND, baseline_ppm=CH4_BACKGROUND,
            random_ppm=sigma, bias_ppm=0.0, detected=bool(e > 3 * sigma),
        )
        for e in excess
    ]


# ── core recovery ────────────────────────────────────────────────────────────
def test_recovers_known_source_position_and_Q():
    true_src, Q_true = (5.0, -3.0), 6.0
    pts = _truth_points(true_src, Q_true)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)

    assert est.converged is True
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.y == pytest.approx(true_src[1], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)
    # Noiseless data fit by its own model → residuals far below the sensor noise
    # floor (the downwind axis is a soft direction, so this is the honest bar, not
    # machine-zero — position/Q above are already within tolerance).
    assert est.rmse_ppm < SENSOR_NOISE_PPM


# Non-cardinal wind: real Open-Meteo wind blows at arbitrary angles, but every
# recovery test above uses 270° (where the coordinate rotation is the identity).
# This drives the whole forward→inverse pipeline at φ=200° and must still localize.
# A downwind fan to the N/NE (downwind ≈ (0.34, 0.94) at 200°), 50–112 m downwind.
SENSORS_NC = np.array([[10.0, 50.0], [30.0, 65.0], [20.0, 90.0], [40.0, 105.0]])
WIND_DIR_NC = 200.0


def test_round_trip_recovers_source_off_cardinal():
    """F1: forward→inverse at a NON-cardinal wind (200°) must recover the source.
    Catches gross rotation sign/transpose bugs end-to-end. NOTE: forward and inverse
    share predict_ppm's inline rotation, so this is an INTEGRATION guard — the
    independent anchors for rotation are the known-answer + non-cardinal equivalence
    tests in test_plume.py; this confirms the inversion itself works off-cardinal."""
    true_src, Q_true = (5.0, -3.0), 6.0
    pts = _truth_points(true_src, Q_true, sensors=SENSORS_NC, wind_dir=WIND_DIR_NC)
    assert max(p.mean_excess_ppm for p in pts) > 1.0     # non-vacuous: real signal present

    est = inversion.invert(SENSORS_NC, pts, WIND_U, WIND_DIR_NC, stability_class=STAB)
    assert est.converged is True
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.y == pytest.approx(true_src[1], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)


def test_Q_is_linear_closed_form():
    # Doubling every reading must exactly double the recovered Q and not move (x, y):
    # Q* = Σwgd/Σwg² is linear in the data d.
    true_src = (10.0, 4.0)
    base = inversion.invert(SENSORS, _truth_points(true_src, 4.0), WIND_U, WIND_DIR,
                            stability_class=STAB)
    doubled_pts = _truth_points(true_src, 8.0)     # = 2× the excess everywhere
    dbl = inversion.invert(SENSORS, doubled_pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert dbl.Q == pytest.approx(2.0 * base.Q, rel=1e-3)
    assert dbl.x == pytest.approx(base.x, abs=1e-6)
    assert dbl.y == pytest.approx(base.y, abs=1e-6)


def test_estimates_stability_class_when_unknown():
    # Generate at class B (2); invert with stability unknown → it should pick 2,
    # because only the true class makes the across-sensor SHAPE fit at zero cost.
    true_src, Q_true = (0.0, 0.0), 5.0
    pts = _truth_points(true_src, Q_true, stability=2)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=None)
    assert est.stability_class == 2
    assert est.Q == pytest.approx(Q_true, rel=0.10)


def test_accepts_plain_mean_sigma_pairs():
    # The (mean_excess_ppm, sigma_ppm) tuple path, not just InversionPoint.
    true_src, Q_true = (8.0, -5.0), 7.0
    total = predict_ppm(true_src, Q_true, WIND_U, WIND_DIR, H, STAB, SENSORS, z=Z)
    pairs = [(float(e - CH4_BACKGROUND), 0.1) for e in total]
    est = inversion.invert(SENSORS, pairs, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)


# ── the CRB referee ──────────────────────────────────────────────────────────
def test_reports_finite_cramer_rao_bound():
    pts = _truth_points((5.0, 0.0), 6.0)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.crb_std is not None
    for key in ("x", "y", "Q"):
        assert key in est.crb_std
        assert np.isfinite(est.crb_std[key]) and est.crb_std[key] > 0


# ── guards & edge cases ──────────────────────────────────────────────────────
def test_quiet_record_is_not_converged():
    # Every sensor reads ~background (no source): Q≈0, position unconstrained, and
    # the estimate is flagged not-converged rather than fabricating a leak.
    pts = [
        InversionPoint(mean_excess_ppm=0.01, sigma_ppm=0.3, n_window=60, window=(0, 60),
                       mean_raw_ppm=1.91, baseline_ppm=1.9, random_ppm=0.3,
                       bias_ppm=0.0, detected=False)
        for _ in SENSORS
    ]
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.converged is False
    assert est.Q == pytest.approx(0.0, abs=0.2)
    assert est.crb_std is None          # skipped when there's nothing to localise


def test_calm_wind_raises():
    pts = _truth_points((5.0, 0.0), 6.0)
    with pytest.raises(ValueError):
        inversion.invert(SENSORS, pts, 0.1, WIND_DIR, stability_class=STAB)


def test_mismatched_lengths_raise():
    pts = _truth_points((5.0, 0.0), 6.0)[:2]    # 2 readings, 4 sensors
    with pytest.raises(ValueError):
        inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)


def test_wide_search_box_is_clamp_safe():
    # A huge box makes the grid probe positions that put sensors <1 m or >200 m
    # downwind; clamp_to_table inside predict_ppm must keep that from raising.
    pts = _truth_points((5.0, 0.0), 6.0)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB,
                           bounds=(-500.0, 500.0, -500.0, 500.0))
    assert np.isfinite(est.x) and np.isfinite(est.Q)


# ── the deployment light switch: raw processed tests → source ────────────────
def test_invert_field_tests_end_to_end():
    # The real entry point: each sensor's processed record → aggregate → invert,
    # in one call. Uses synthetic samples (no fixed truth geometry), so this is a
    # smoke/integration test: it must run the whole raw→source path and return a
    # finite, converged estimate because the samples contain a real event.
    from physics import fieldtest as ft
    results = []
    for seed in range(3):
        s = ft.make_sample_readings(n=600, event_ppm=5.0, seed=seed)
        results.append(ft.process_fieldtest(
            s["ppm"], temperature=s["temperature"], humidity=s["humidity"],
            time=s["time"], noise_ppm=0.30))
    sensors = np.array([[40.0, 0.0], [70.0, 10.0], [100.0, -12.0]])
    est = inversion.invert_field_tests(results, sensors, WIND_U, WIND_DIR,
                                       stability_class=STAB)
    assert est.n_sensors == 3
    assert np.isfinite(est.x) and np.isfinite(est.y) and np.isfinite(est.Q)
    assert est.converged is True
