"""
test_inversion.py — Week-3 source inversion (physics/inversion.py).

Closed-loop philosophy, same as the rest of the suite: build readings from the
forward model for a KNOWN source, then check the inverse recovers it. Because the
data is generated by the very model the inverse fits, a good optimiser must land on
the truth to near machine tolerance (noiseless) — so these pin both the math
(linear-in-Q closed form, stability looping) and the optimiser (shrinking grid).

All pure numpy, no network, no scipy.
"""
import numpy as np
import pytest

from physics.plume import CH4_BACKGROUND, predict_ppm
from physics.sensor_sim import SENSOR_NOISE_PPM
from physics.fieldtest import InversionPoint
from physics import inversion


# Geometry shared by the recovery tests: source west of a fan of downwind sensors
# (wind FROM the west, 270°, so downwind = east). All sensors sit 40–110 m downwind,
# inside the σ table, at varied crosswind offsets so (x, y) is well constrained.
SENSORS = np.array([[40.0, 0.0], [70.0, 12.0], [95.0, -18.0], [110.0, 6.0]])
WIND_U, WIND_DIR, STAB, H, Z = 2.0, 270.0, 4, 1.0, 1.0


def _truth_points(true_src, Q_true, sigma=0.1, stability=STAB,
                  sensors=SENSORS, wind_dir=WIND_DIR):
    """Noiseless InversionPoints for a known source — excess from the forward model.

    ``sensors``/``wind_dir`` default to the shared 270° geometry; the non-cardinal
    round-trip test overrides them (the defaults keep every other caller unchanged).
    """
    total = predict_ppm(true_src, Q_true, WIND_U, wind_dir, H, stability, sensors, z=Z)
    excess = total - CH4_BACKGROUND
    return [
        InversionPoint(
            mean_excess_ppm=float(e), sigma_ppm=sigma, n_window=60, window=(0, 60),
            mean_raw_ppm=float(e) + CH4_BACKGROUND, baseline_ppm=CH4_BACKGROUND,
            random_ppm=sigma, bias_ppm=0.0, detected=bool(e > 3 * sigma),
        )
        for e in excess
    ]


# ── core recovery ────────────────────────────────────────────────────────────
def test_recovers_known_source_position_and_Q():
    true_src, Q_true = (5.0, -3.0), 6.0
    pts = _truth_points(true_src, Q_true)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)

    assert est.converged is True
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.y == pytest.approx(true_src[1], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)
    # Noiseless data fit by its own model → residuals far below the sensor noise
    # floor (the downwind axis is a soft direction, so this is the honest bar, not
    # machine-zero — position/Q above are already within tolerance).
    assert est.rmse_ppm < SENSOR_NOISE_PPM


# Non-cardinal wind: real Open-Meteo wind blows at arbitrary angles, but every
# recovery test above uses 270° (where the coordinate rotation is the identity).
# This drives the whole forward→inverse pipeline at φ=200° and must still localize.
# A downwind fan to the N/NE (downwind ≈ (0.34, 0.94) at 200°), 50–112 m downwind.
SENSORS_NC = np.array([[10.0, 50.0], [30.0, 65.0], [20.0, 90.0], [40.0, 105.0]])
WIND_DIR_NC = 200.0


def test_round_trip_recovers_source_off_cardinal():
    """F1: forward→inverse at a NON-cardinal wind (200°) must recover the source.
    Catches gross rotation sign/transpose bugs end-to-end. NOTE: forward and inverse
    share predict_ppm's inline rotation, so this is an INTEGRATION guard — the
    independent anchors for rotation are the known-answer + non-cardinal equivalence
    tests in test_plume.py; this confirms the inversion itself works off-cardinal."""
    true_src, Q_true = (5.0, -3.0), 6.0
    pts = _truth_points(true_src, Q_true, sensors=SENSORS_NC, wind_dir=WIND_DIR_NC)
    assert max(p.mean_excess_ppm for p in pts) > 1.0     # non-vacuous: real signal present

    est = inversion.invert(SENSORS_NC, pts, WIND_U, WIND_DIR_NC, stability_class=STAB)
    assert est.converged is True
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.y == pytest.approx(true_src[1], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)


def test_Q_is_linear_closed_form():
    # Doubling every reading must exactly double the recovered Q and not move (x, y):
    # Q* = Σwgd/Σwg² is linear in the data d.
    true_src = (10.0, 4.0)
    base = inversion.invert(SENSORS, _truth_points(true_src, 4.0), WIND_U, WIND_DIR,
                            stability_class=STAB)
    doubled_pts = _truth_points(true_src, 8.0)     # = 2× the excess everywhere
    dbl = inversion.invert(SENSORS, doubled_pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert dbl.Q == pytest.approx(2.0 * base.Q, rel=1e-3)
    assert dbl.x == pytest.approx(base.x, abs=1e-6)
    assert dbl.y == pytest.approx(base.y, abs=1e-6)


def test_estimates_stability_class_when_unknown():
    # Generate at class B (2); invert with stability unknown → it should pick 2,
    # because only the true class makes the across-sensor SHAPE fit at zero cost.
    true_src, Q_true = (0.0, 0.0), 5.0
    pts = _truth_points(true_src, Q_true, stability=2)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=None)
    assert est.stability_class == 2
    assert est.Q == pytest.approx(Q_true, rel=0.10)


def test_accepts_plain_mean_sigma_pairs():
    # The (mean_excess_ppm, sigma_ppm) tuple path, not just InversionPoint.
    true_src, Q_true = (8.0, -5.0), 7.0
    total = predict_ppm(true_src, Q_true, WIND_U, WIND_DIR, H, STAB, SENSORS, z=Z)
    pairs = [(float(e - CH4_BACKGROUND), 0.1) for e in total]
    est = inversion.invert(SENSORS, pairs, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.x == pytest.approx(true_src[0], abs=3.0)
    assert est.Q == pytest.approx(Q_true, rel=0.05)


# ── the CRB referee ──────────────────────────────────────────────────────────
def test_reports_finite_cramer_rao_bound():
    pts = _truth_points((5.0, 0.0), 6.0)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.crb_std is not None
    for key in ("x", "y", "Q"):
        assert key in est.crb_std
        assert np.isfinite(est.crb_std[key]) and est.crb_std[key] > 0


# ── guards & edge cases ──────────────────────────────────────────────────────
def test_quiet_record_is_not_converged():
    # Every sensor reads ~background (no source): Q≈0, position unconstrained, and
    # the estimate is flagged not-converged rather than fabricating a leak.
    pts = [
        InversionPoint(mean_excess_ppm=0.01, sigma_ppm=0.3, n_window=60, window=(0, 60),
                       mean_raw_ppm=1.91, baseline_ppm=1.9, random_ppm=0.3,
                       bias_ppm=0.0, detected=False)
        for _ in SENSORS
    ]
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)
    assert est.converged is False
    assert est.Q == pytest.approx(0.0, abs=0.2)
    assert est.crb_std is None          # skipped when there's nothing to localise


def test_pure_noise_does_not_fabricate_a_source():
    # F6: sourceless records (pure background + sensor noise, NO event) must not be
    # flagged converged. Truth is independent of the inversion — there is no source,
    # so converged=True is always wrong. The low-percentile baseline leaves a small
    # POSITIVE offset in mean_excess that the old 3·σ-of-the-mean gate mistook for
    # signal on ~half of all sourceless multi-sensor records. Gate on the per-sample
    # detection floor instead, and the rate must stay low.
    from physics import fieldtest as ft
    trials, fabricated = 50, 0
    for seed in range(trials):
        rng = np.random.default_rng(50_000 + seed)
        results = [
            ft.process_fieldtest(CH4_BACKGROUND + rng.normal(0, 0.30, size=400),
                                 noise_ppm=0.30)
            for _ in SENSORS
        ]
        est = inversion.invert_field_tests(results, SENSORS, WIND_U, WIND_DIR,
                                           stability_class=STAB)
        fabricated += int(est.converged)
    # No source exists → the fabrication rate must stay well under the old ~50%.
    # A small residual just reflects detect_pattern's own false-positive rate.
    assert fabricated / trials <= 0.15, f"fabricated {fabricated}/{trials} from noise"


def test_calm_wind_raises():
    pts = _truth_points((5.0, 0.0), 6.0)
    with pytest.raises(ValueError):
        inversion.invert(SENSORS, pts, 0.1, WIND_DIR, stability_class=STAB)


def test_mismatched_lengths_raise():
    pts = _truth_points((5.0, 0.0), 6.0)[:2]    # 2 readings, 4 sensors
    with pytest.raises(ValueError):
        inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)


def test_wide_search_box_is_clamp_safe():
    # A huge box makes the grid probe positions that put sensors <1 m or >200 m
    # downwind; clamp_to_table inside predict_ppm must keep that from raising.
    # NOTE (F7): extreme user-specified bounds (>> 150 m pad) widen the spurious-basin
    # problem, but they are NOT its only cause — even the default bounds can land in a
    # wrong basin under realistic single-wind data. Only finiteness is asserted here;
    # recovery (and its multi-snapshot cure) is exercised by the F7 tests below.
    pts = _truth_points((5.0, 0.0), 6.0)
    est = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB,
                           bounds=(-500.0, 500.0, -500.0, 500.0))
    assert np.isfinite(est.x) and np.isfinite(est.Q)


# Sensors all on the plume centreline (y=0, same as the true source). x is
# well-constrained by varying downwind distances, but y sensitivity is near-zero
# at the exact centreline — measuring the CRB asymmetry characterises F7.
SENSORS_COLLINEAR = np.array([[40.0, 0.0], [60.0, 0.0], [80.0, 0.0], [100.0, 0.0]])


def test_collinear_sensors_crb_flags_ill_posedness():
    # F7: sensors all at y=0 are nearly blind to y_src. The Gaussian crosswind
    # gradient ∂ppm/∂y_src = ppm·(y_wind/σ_y²) is near-zero when all y_wind ≈ 0,
    # so the Fisher info for y is tiny → crb_std["y"] >> crb_std["x"]. Recovery of
    # x and Q is still correct because sensors span a range of downwind distances.
    # This characterises the "collinear → ill-posed in crosswind" branch of F7.
    true_src, Q_true = (5.0, 0.0), 8.0
    pts = _truth_points(true_src, Q_true, sensors=SENSORS_COLLINEAR)
    est = inversion.invert(SENSORS_COLLINEAR, pts, WIND_U, WIND_DIR,
                           stability_class=STAB)
    assert est.converged is True
    assert est.x == pytest.approx(true_src[0], abs=3.0)   # x is well-constrained; same bar as core test
    assert est.Q == pytest.approx(Q_true, rel=0.10)
    assert abs(est.y) < 50.0                               # not physically precise, but not lost
    # y is poorly constrained: its CRB must be >> x CRB (independent ground truth:
    # ∂ppm/∂y_src ≈ 0 on the centreline → Fisher info for y is tiny).
    assert est.crb_std is not None
    assert est.crb_std["y"] > est.crb_std["x"] * 3


# ── F7: a REALISTIC hard dataset, and the multi-snapshot fix ─────────────────
# Everything above feeds the inversion noiseless excess straight from predict_ppm,
# so a good optimiser must hit the truth. Real deployments are not that kind: the
# readings carry sensor noise, baseline drift, and weather, and the geometry is a
# fenceline where ONE near sensor sees a strong plume while the others read ~bkg.
# This builder makes exactly that dataset through the FULL deployment pipeline
# (sensor_sim → process_fieldtest → invert_field_tests), so it is what Custer/
# Melissa data will look like — not a toy. F7's lesson: one wind on this geometry is
# under-determined (only ~2 sensors carry real signal for 3 unknowns x,y,Q), so the
# single-snapshot fit is silently ~28 m off; watching the leak under SEVERAL winds
# (invert_multi) triangulates it back to sub-metre. Both are pinned below.

def _realistic_field_results(sensors, true_src, Q_true, u=WIND_U, wind_dir=WIND_DIR,
                             stability=STAB, n=600, noise=0.30, drift=1.0, seed0=0):
    """Build N per-sensor processed records for a known (true_src, Q) leak.

    Each sensor's steady-state excess comes from the forward model; that excess is
    then buried in a realistic raw record (background + slow drift + temp/humidity
    + Gaussian noise) and run back through the SAME cleaning pipeline a real upload
    uses. Deterministic given the seeds. Returns the list `invert_field_tests` eats.
    """
    from physics import fieldtest as ft
    excess = predict_ppm(true_src, Q_true, u, wind_dir, H, stability, sensors,
                         z=Z) - CH4_BACKGROUND
    results = []
    for i, e in enumerate(excess):
        true = ft.make_plume_event(n, event_ppm=float(max(e, 0.0)))
        data = ft.synthetic_timeseries(true, noise_ppm=noise, drift_ppm=drift,
                                       with_weather=True, seed=seed0 + i)
        results.append(ft.process_fieldtest(
            data.raw, temperature=data.temperature, humidity=data.humidity,
            time=data.time, noise_ppm=noise))
    return results


# A plausible fenceline: source upwind in the yard, sensors at varied downwind
# distances. The nearest sensor sees a large plume while the others see almost
# nothing → a near/far Q-distance ridge along the wind axis. (100% reproducible
# across seeds in exploration; the default seed is locked here.)
SENSORS_F7 = np.array([[30.0, 0.0], [90.0, -25.0], [95.0, 20.0], [110.0, -5.0]])
TRUE_SRC_F7, Q_F7 = (15.0, 2.0), 4.0


# Wind veers ±20° over a multi-hour deployment; each direction is one snapshot.
WINDS_F7 = (250.0, 270.0, 290.0)


def test_f7_single_snapshot_is_under_determined():
    # The honest known LIMIT of a single wind on this geometry (not a code bug fixable
    # in single-snapshot mode): only ~2 sensors carry real signal, so (x,y,Q) is
    # under-determined and the fit lands far from truth WITHOUT crashing — a silent
    # miss. Truth is independent of the inversion (we built the data from it). This is
    # exactly why invert_multi exists; the next test cures it on the SAME geometry.
    results = _realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7)
    est = inversion.invert_field_tests(results, SENSORS_F7, WIND_U, WIND_DIR,
                                       stability_class=STAB)
    assert est.n_snapshots == 1
    assert est.converged is True                 # silent failure, not a crash
    pos_err = float(np.hypot(est.x - TRUE_SRC_F7[0], est.y - TRUE_SRC_F7[1]))
    assert pos_err > 15.0                         # confidently wrong from one snapshot


def test_f7_multi_snapshot_fusion_recovers_source():
    # THE F7 FIX (actually reduces the error): the same under-determined fenceline,
    # watched under three wind directions, is triangulated. Each snapshot is built from
    # the SAME (src, Q) through the full pipeline at its own wind + an independent noise
    # seed, then fused (shared Q, joint (x,y) grid search). ~28 m single-wind error
    # collapses to sub-metre — and the truth is independent ground truth, so this is a
    # real recovery, not a fit to itself.
    snaps = [(_realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7,
                                       wind_dir=wd, seed0=1000 * j),
              WIND_U, wd, STAB)
             for j, wd in enumerate(WINDS_F7)]
    fused = inversion.invert_field_tests_multi(snaps, SENSORS_F7, stability_class=STAB)
    assert fused.n_snapshots == 3
    assert fused.converged is True
    pos_err = float(np.hypot(fused.x - TRUE_SRC_F7[0], fused.y - TRUE_SRC_F7[1]))
    assert pos_err < 5.0                          # vs > 15 m single-snapshot (above)
    assert fused.Q == pytest.approx(Q_F7, rel=0.2)


def test_f7_multi_snapshot_crb_tightens():
    # Fisher information ADDS across snapshots (crb_source_bound_multi), so fusing winds
    # can only tighten the best-possible bound. Independent of the optimiser: compare
    # the combined CRB to the single-wind CRB at the same source.
    single = inversion.invert_field_tests(
        _realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7, wind_dir=270.0),
        SENSORS_F7, WIND_U, 270.0, stability_class=STAB)
    snaps = [(_realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7,
                                       wind_dir=wd, seed0=1000 * j),
              WIND_U, wd, STAB)
             for j, wd in enumerate(WINDS_F7)]
    fused = inversion.invert_field_tests_multi(snaps, SENSORS_F7, stability_class=STAB)
    assert fused.crb_std["x"] < single.crb_std["x"]
    assert fused.crb_std["y"] < single.crb_std["y"]


def test_invert_multi_equals_invert_for_single_snapshot():
    # invert() IS invert_multi() with one snapshot — the K=1 path must match exactly
    # (same optimiser knobs), proving the refactor preserved the single-wind behaviour.
    pts = _truth_points((5.0, -3.0), 6.0)
    a = inversion.invert(SENSORS, pts, WIND_U, WIND_DIR, stability_class=STAB)
    b = inversion.invert_multi(SENSORS, [inversion.Snapshot(pts, WIND_U, WIND_DIR)],
                               stability_class=STAB, coarse=28, n_seeds=6)
    assert b.n_snapshots == 1
    assert b.x == pytest.approx(a.x, abs=1e-9)
    assert b.y == pytest.approx(a.y, abs=1e-9)
    assert b.Q == pytest.approx(a.Q, abs=1e-9)


def test_multi_snapshot_tolerates_a_blind_snapshot():
    # A wind from the EAST (90°) pushes the plume WEST, away from sensors east of the
    # source → every reading ~background, so that snapshot's modelled shape g≈0 and the
    # shared-Q denominator is ~0. The guard must avoid a divide-by-zero, and the two
    # informative winds must still localise to a finite, converged source.
    snaps = [
        (_realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7, wind_dir=270.0, seed0=0),
         WIND_U, 270.0, STAB),
        (_realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7, wind_dir=90.0, seed0=500),
         WIND_U, 90.0, STAB),
        (_realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7, wind_dir=290.0, seed0=1500),
         WIND_U, 290.0, STAB),
    ]
    est = inversion.invert_field_tests_multi(snaps, SENSORS_F7, stability_class=STAB)
    assert np.isfinite(est.x) and np.isfinite(est.y) and np.isfinite(est.Q)
    assert est.converged is True


def test_invert_multi_fits_when_each_snapshot_carries_its_own_stability():
    # stability_class=None AND every snapshot supplies its OWN class → a single pass that
    # uses each snapshot's class, no class fitting and no crash. Pins the resolution path
    # (trial is None here) that a reviewer suspected could TypeError — it does not.
    src, Q, stab = (5.0, -3.0), 6.0, 3
    snaps = [inversion.Snapshot(_truth_points(src, Q, stability=stab, wind_dir=wd),
                                WIND_U, wd, stability_class=stab)
             for wd in (260.0, 280.0)]
    est = inversion.invert_multi(SENSORS, snaps, stability_class=None)
    assert est.n_snapshots == 2
    assert est.stability_class == stab            # used each snapshot's class, didn't refit
    assert est.x == pytest.approx(src[0], abs=3.0)
    assert est.Q == pytest.approx(Q, rel=0.1)


def test_f7_realistic_dataset_is_well_posed_for_the_fit():
    # Guard the LEVER, not the bug: confirm the hard dataset is genuinely solvable —
    # it carries real signal (so the wrong answer is a localisation failure, not an
    # absent plume), and the inversion converges (the trap is silent, not a crash).
    # This must stay GREEN even while the bug test above xfails.
    results = _realistic_field_results(SENSORS_F7, TRUE_SRC_F7, Q_F7)
    pts = [inversion.aggregate_for_inversion(r) for r in results]
    assert max(p.mean_excess_ppm for p in pts) > 3 * 0.30   # a real, detectable plume
    est = inversion.invert_field_tests(results, SENSORS_F7, WIND_U, WIND_DIR,
                                       stability_class=STAB)
    assert est.converged is True                            # the failure is silent
    assert est.Q == pytest.approx(Q_F7, rel=0.5)            # Q roughly sane; position is the casualty


# ── the deployment light switch: raw processed tests → source ────────────────
def test_invert_field_tests_end_to_end():
    # The real entry point: each sensor's processed record → aggregate → invert,
    # in one call. Uses synthetic samples (no fixed truth geometry), so this is a
    # smoke/integration test: it must run the whole raw→source path and return a
    # finite, converged estimate because the samples contain a real event.
    from physics import fieldtest as ft
    results = []
    for seed in range(3):
        s = ft.make_sample_readings(n=600, event_ppm=5.0, seed=seed)
        results.append(ft.process_fieldtest(
            s["ppm"], temperature=s["temperature"], humidity=s["humidity"],
            time=s["time"], noise_ppm=0.30))
    sensors = np.array([[40.0, 0.0], [70.0, 10.0], [100.0, -12.0]])
    est = inversion.invert_field_tests(results, sensors, WIND_U, WIND_DIR,
                                       stability_class=STAB)
    assert est.n_sensors == 3
    assert np.isfinite(est.x) and np.isfinite(est.y) and np.isfinite(est.Q)
    assert est.converged is True
